"""
@author Chantal Li
@desc 从HGVS格式生成变体fasta序列
@date 2021/12/10

    Input: fasta_path(string), protein_HGVS(string), variant_type(int)
    Output: [HGVS].fasta
    Retrun: 0/variant_type
"""

import re
import sys

try:
    # input parameters
    fasta_path = sys.argv[1]
    protein_HGVS = sys.argv[2]
    variant_type = int(sys.argv[3])
    result_path = sys.argv[4]
    
    BRCA1_WILD = 'MDLSALRVEEVQNVINAMQKILECPICLELIKEPVSTKCDHIFCKFCMLKLLNQKKGPSQCPLCKNDITKRSLQESTRFSQLVEELLKIICAFQLDTGLEYANSYNFAKKENNSPEHLKDEVSIIQSMGYRNRAKRLLQSEPENPSLQETSLSVQLSNLGTVRTLRTKQRIQPQKTSVYIELGSDSSEDTVNKATYCSVGDQELLQITPQGTRDEISLDSAKKAACEFSETDVTNTEHHQPSNNDLNTTEKRAAERHPEKYQGSSVSNLHVEPCGTNTHASSLQHENSSLLLTKDRMNVEKAEFCNKSKQPGLARSQHNRWAGSKETCNDRRTPSTEKKVDLNADPLCERKEWNKQKLPCSENPRDTEDVPWITLNSSIQKVNEWFSRSDELLGSDDSHDGESESNAKVADVLDVLNEVDEYSGSSEKIDLLASDPHEALICKSERVHSKSVESNIEDKIFGKTYRKKASLPNLSHVTENLIIGAFVTEPQIIQERPLTNKLKRKRRPTSGLHPEDFIKKADLAVQKTPEMINQGTNQTEQNGQVMNITNSGHENKTKGDSIQNEKNPNPIESLEKESAFKTKAEPISSSISNMELELNIHNSKAPKKNRLRRKSSTRHIHALELVVSRNLSPPNCTELQIDSCSSSEEIKKKKYNQMPVRHSRNLQLMEGKEPATGAKKSNKPNEQTSKRHDSDTFPELKLTNAPGSFTKCSNTSELKEFVNPSLPREEKEEKLETVKVSNNAEDPKDLMLSGERVLQTERSVESSSISLVPGTDYGTQESISLLEVSTLGKAKTEPNKCVSQCAAFENPKGLIHGCSKDNRNDTEGFKYPLGHEVNHSRETSIEMEESELDAQYLQNTFKVSKRQSFAPFSNPGNAEEECATFSAHSGSLKKQSPKVTFECEQKEENQGKNESNIKPVQTVNITAGFPVVGQKDKPVDNAKCSIKGGSRFCLSSQFRGNETGLITPNKHGLLQNPYRIPPLFPIKSFVKTKCKKNLLEENFEEHSMSPEREMGNENIPSTVSTISRNNIRENVFKEASSSNINEVGSSTNEVGSSINEIGSSDENIQAELGRNRGPKLNAMLRLGVLQPEVYKQSLPGSNCKHPEIKKQEYEEVVQTVNTDFSPYLISDNLEQPMGSSHASQVCSETPDDLLDDGEIKEDTSFAENDIKESSAVFSKSVQKGELSRSPSPFTHTHLAQGYRRGAKKLESSEENLSSEDEELPCFQHLLFGKVNNIPSQSTRHSTVATECLSKNTEENLLSLKNSLNDCSNQVILAKASQEHHLSEETKCSASLFSSQCSELEDLTANTNTQDPFLIGSSKQMRHQSESQGVGLSDKELVSDDEERGTGLEENNQEEQSMDSNLGEAASGCESETSVSEDCSGLSSQSDILTTQQRDTMQHNLIKLQQEMAELEAVLEQHGSQPSNSYPSIISDSSALEDLRNPEQSTSEKAVLTSQKSSEYPISQNPEGLSADKFEVSADSSTSKNKEPGVERSSPSKCPSLDDRWYMHSCSGSLQNRNYPSQEELIKVVDVEEQQLEESGPHDLTETSYLPRQDLEGTPYLESGISLFSDDPESDPSEDRAPESARVGNIPSSTSALKVPQLKVAESAQSPAAAHTTDTAGYNAMEESVSREKPELTASTERVNKRMSMVVSGLTPEEFMLVYKFARKHHITLTNLITEETTHVVMKTDAEFVCERTLKYFLGIAGGKWVVSYFWVTQSIKERKMLNEHDFEVRGDVVNGRNHQGPKRARESQDRKIFRGLEICCYGPFTNMPTDQLEWMVQLCGASVVKELSSFTLGTGVHPIVVVQPDAWTEDNGFHAIGQMCEAPVVTREWVLDSVALYQCQELDTYLIPQIPHSHY'
    protein_dict = {'Ala': 'A', 'Cys': 'C', 'Asp': 'D', 'Glu': 'E', 'Phe': 'F', 'Gly': 'G', 'His': 'H', 'Ile': 'I', 'Lys': 'K', 'Leu': 'L',
                        'Met': 'M', 'Asn': 'N', 'Arg': 'R', 'Pro': 'P', 'Gln': 'Q', 'Ser': 'S', 'Thr': 'T', 'Val': 'V', 'Trp': 'W', 'Tyr': 'Y'}
    
    if(variant_type == 1):
    # missense mutation in BRCT domain of BRCA1
        if (re.match('^[a-zA-Z]{3}[0-9]{4}[a-zA-Z]{3}$', protein_HGVS)):
            var_pos = int(protein_HGVS[3:-3])
            if (var_pos > 1645) & (var_pos < 1860):
                old_amino = protein_HGVS[:3]
                new_amino = protein_HGVS[-3:]
                if (old_amino == new_amino):
                    with open(result_path, 'w') as f:
                        f.write('0.0000041723251343')
                        sys.exit(2)
    
                if (new_amino != 'Ter') & (new_amino != 'del') & (new_amino != 'dup'):
                    seq = list(BRCA1_WILD)
                    if seq[var_pos-1] == protein_dict[old_amino]:
                        seq[var_pos-1] = protein_dict[new_amino]
                        BRCT_Var = ''.join(seq[1645:1859])
                        label = '>NP_009225.1 breast cancer type 1 susceptibility protein BRCT variant %s [Homo sapiens]' % (protein_HGVS)
                        with open(fasta_path, 'w') as f:
                            f.write(label + '\n' + BRCT_Var)
                    else:
                        raise Exception("pos %d is not %s" % (var_pos, old_amino))
                else:
                    raise Exception('del or Ter or dup')
            else:
                raise Exception("not BRCT missense")
        else:
            raise Exception("not BRCT missense")
    else:
        raise Exception("error variant_type")
except:
    sys.exit(0)
sys.exit(1)
